# test
name: Publish to NPM on push to main

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.npm_token }}